use binlens::types::{BinaryReport, DiffReport};

#[allow(dead_code)]
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum GateStatus {
    Passed,
    Degraded,
    Failed,
    Warning,
}

#[derive(Debug, Clone)]
pub struct GateFinding {
    pub rule_id: String,
    pub title: String,
    pub description: String,
    #[allow(dead_code)]
    pub status: GateStatus,
    pub severity: String, // "error", "warning", "info"
}

pub fn render_markdown_summary(
    target: &BinaryReport,
    baseline: Option<&BinaryReport>,
    diff: Option<&DiffReport>,
    findings: &[GateFinding],
    passed: bool,
) -> String {
    let mut out = String::new();

    let badge = if passed {
        "### 🟢 Relgate Security Gate: **PASSED**"
    } else {
        "### 🔴 Relgate Security Gate: **FAILED (Release Blocked)**"
    };

    out.push_str(badge);
    out.push_str("\n\n");

    out.push_str(&format!(
        "| Metric | Target Asset | Baseline (Previous) | Status |\n\
         | :--- | :--- | :--- | :--- |\n\
         | **Binary Name** | `{}` | `{}` | - |\n\
         | **Format / Arch** | {} / {} | {} | - |\n\
         | **File Size** | {} bytes | {} | {} |\n\
         | **Shannon Entropy** | {:.3} / 8.000 | {} | {} |\n\
         | **ASLR / PIE** | {} | {} | {} |\n\
         | **DEP / NX** | {} | {} | {} |\n\
         | **W^X (No RWX)** | {} | {} | {} |\n\
         | **Authenticode** | {} | {} | {} |\n\n",
        target.file_name,
        baseline.map(|b| b.file_name.as_str()).unwrap_or("N/A"),
        target.format,
        target.architecture,
        baseline
            .map(|b| format!("{} / {}", b.format, b.architecture))
            .unwrap_or_else(|| "-".into()),
        target.file_size,
        baseline
            .map(|b| format!("{} bytes", b.file_size))
            .unwrap_or_else(|| "-".into()),
        diff.map(|d| format_delta_bytes(d.size_delta))
            .unwrap_or_else(|| "-".into()),
        target.overall_entropy,
        baseline
            .map(|b| format!("{:.3}", b.overall_entropy))
            .unwrap_or_else(|| "-".into()),
        if target.overall_entropy > 7.2 {
            "⚠️ High"
        } else {
            "🟢 Normal"
        },
        format_mitigation(target.mitigations.aslr || target.mitigations.pie),
        baseline
            .map(|b| format_mitigation(b.mitigations.aslr || b.mitigations.pie))
            .unwrap_or("-"),
        diff_status(diff, "aslr"),
        format_mitigation(target.mitigations.dep_nx),
        baseline
            .map(|b| format_mitigation(b.mitigations.dep_nx))
            .unwrap_or("-"),
        diff_status(diff, "dep_nx"),
        if target.mitigations.has_rwx_sections {
            "🔴 RWX Present"
        } else {
            "🟢 Enforced"
        },
        baseline
            .map(|b| if b.mitigations.has_rwx_sections {
                "🔴 RWX Present"
            } else {
                "🟢 Enforced"
            })
            .unwrap_or("-"),
        if target.mitigations.has_rwx_sections {
            "🔴 VIOLATION"
        } else {
            "🟢 OK"
        },
        format_authenticode(target),
        baseline
            .map(format_authenticode)
            .unwrap_or_else(|| "-".into()),
        authenticode_status(target),
    ));

    if !findings.is_empty() {
        out.push_str("#### 🔍 Gate Findings & Policy Violations\n\n");
        out.push_str("| Severity | Rule ID | Details |\n| :--- | :--- | :--- |\n");
        for f in findings {
            let icon = match f.severity.as_str() {
                "error" => "🔴 **ERROR**",
                "warning" => "⚠️ **WARN**",
                _ => "ℹ️ **INFO**",
            };
            out.push_str(&format!(
                "| {} | `{}` | **{}**: {} |\n",
                icon, f.rule_id, f.title, f.description
            ));
        }
        out.push('\n');
    }

    if let Some(d) = diff {
        if !d.section_deltas.is_empty() {
            out.push_str("#### 📦 Section Layout Changes\n\n");
            out.push_str("| Action | Section | Size Delta |\n| :--- | :--- | :--- |\n");
            for s in &d.section_deltas {
                out.push_str(&format!(
                    "| `{}` | `{}` | {} bytes |\n",
                    s.action, s.name, s.size_delta
                ));
            }
            out.push('\n');
        }
    }

    out.push_str("> *Automated binary release gate generated by [relgate](https://github.com/raidshadowmc-sudo/relgate)*\n");
    out
}

fn format_mitigation(val: bool) -> &'static str {
    if val { "🟢 Enabled" } else { "🔴 Disabled" }
}

fn format_delta_bytes(delta: i64) -> String {
    use std::cmp::Ordering;
    match delta.cmp(&0) {
        Ordering::Greater => format!("+{} bytes", delta),
        Ordering::Less => format!("{} bytes", delta),
        Ordering::Equal => "0 bytes".to_string(),
    }
}

fn diff_status(diff: Option<&DiffReport>, mit: &str) -> &'static str {
    if let Some(d) = diff {
        for m in &d.mitigations_drift {
            if m.mitigation.to_lowercase().contains(mit) {
                return match m.status.as_str() {
                    "hardened" => "🟢 Hardened",
                    "degraded" => "🔴 DEGRADED",
                    _ => "⚪ Unchanged",
                };
            }
        }
    }
    "-"
}

fn format_authenticode(rep: &BinaryReport) -> String {
    if let Some(ref auth) = rep.authenticode {
        match auth.status {
            binlens::types::AuthenticodeStatus::DigestMatch => "🟢 Valid (DigestMatch)".into(),
            binlens::types::AuthenticodeStatus::DigestMismatch => {
                "🔴 Tampered (DigestMismatch)".into()
            }
            binlens::types::AuthenticodeStatus::Malformed => "🔴 Malformed".into(),
            binlens::types::AuthenticodeStatus::NotSigned => "⚪ Unsigned".into(),
        }
    } else {
        "⚪ Unsigned".into()
    }
}

fn authenticode_status(rep: &BinaryReport) -> &'static str {
    if let Some(ref auth) = rep.authenticode {
        match auth.status {
            binlens::types::AuthenticodeStatus::DigestMatch => "🟢 OK",
            binlens::types::AuthenticodeStatus::DigestMismatch => "🔴 FAIL",
            binlens::types::AuthenticodeStatus::Malformed => "🔴 FAIL",
            binlens::types::AuthenticodeStatus::NotSigned => "⚪",
        }
    } else {
        "⚪"
    }
}
